 //using hostname.

//[code language="java"]
node {

    maven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/t1191578/sprinapp_sample_microserviceapp.git', CredentialsID: 'gitt1191578', branch: 'master'
        }

        stage('Build') {
            sh 'clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "gksp23/account-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("gksp23/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}
