node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/t1191578/sprinapp_sample_microserviceapp.git'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('customer-service') {
                def app = docker.build "gksp23/customer-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("gksp23/customer-service:${env.version}").run('-p 3333:3333 -h customer --name customer --link discovery --link account')
        }

        stage ('Final') {
          # build job: 'build', wait: false
        }      

    }

}
